export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_CLEANUP = 'LOGIN_CLEANUP';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGOUT_CLEANUP = 'LOGOUT_CLEANUP';

export const GET_STATES_START = 'GET_STATES_START';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAIL = 'GET_STATES_FAIL';
export const GET_STATES_CLEANUP = 'GET_STATES_CLEANUP';

export const GET_FLIGHTS_ARRIVAL_START = 'GET_FLIGHTS_ARRIVAL_START';
export const GET_FLIGHTS_ARRIVAL_SUCCESS = 'GET_FLIGHTS_ARRIVAL_SUCCESS';
export const GET_FLIGHTS_ARRIVAL_FAIL = 'GET_FLIGHTS_ARRIVAL_FAIL';
export const GET_FLIGHTS_ARRIVAL_CLEANUP = 'GET_FLIGHTS_ARRIVAL_CLEANUP';

export const GET_FLIGHTS_DEPARTURE_START = 'GET_FLIGHTS_DEPARTURE_START';
export const GET_FLIGHTS_DEPARTURE_SUCCESS = 'GET_FLIGHTS_DEPARTURE_SUCCESS';
export const GET_FLIGHTS_DEPARTURE_FAIL = 'GET_FLIGHTS_DEPARTURE_FAIL';
export const GET_FLIGHTS_DEPARTURE_CLEANUP = 'GET_FLIGHTS_DEPARTURE_CLEANUP';
